# Generated by Django 5.2.8 on 2025-11-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('organizer', models.CharField(blank=True, max_length=200)),
                ('start_year', models.CharField(blank=True, max_length=10)),
                ('period', models.CharField(blank=True, max_length=120)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='festivals.festival')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
