# Generated by Django 5.2.8 on 2025-11-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festival',
            options={'ordering': ['start_date', 'title']},
        ),
        migrations.RemoveField(
            model_name='festival',
            name='category',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='link',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='period',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='start_year',
        ),
        migrations.AddField(
            model_name='festival',
            name='address_lot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='festival',
            name='address_road',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='festival',
            name='data_reference_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='extra_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='homepage',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='host',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='festival',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='festival',
            name='sponsor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='festival',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, unique=True),
        ),
    ]
